GRANT SELECT ON [NEW].[DimTrip_type] TO [NT SERVICE\MSOLAP$SERVEUR1];
GRANT SELECT ON [NEW].[DimCity] TO [NT SERVICE\MSOLAP$SERVEUR1];
GRANT SELECT ON [NEW].[DimRoute] TO [NT SERVICE\MSOLAP$SERVEUR1];
GRANT SELECT ON  [NEW].[DimYear]TO [NT SERVICE\MSOLAP$SERVEUR1];
GRANT SELECT ON [NEW].[DimSale_channels] TO [NT SERVICE\MSOLAP$SERVEUR1];
GRANT SELECT ON [NEW].[Factreview] TO [NT SERVICE\MSOLAP$SERVEUR1];

