USE [master]
GO
GO
USE [project] 
GO

CREATE TABLE [NEW].[DimCity](
	[CityID] [int] IDENTITY(1,1) NOT NULL,
	[City] [varchar](100) NULL,
	[RouteID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [NEW].[DimCity]  WITH CHECK ADD  CONSTRAINT [FK_RouteID] FOREIGN KEY([RouteID])
REFERENCES [NEW].[DimRoute] ([RouteID])
GO

ALTER TABLE [NEW].[DimCity] CHECK CONSTRAINT [FK_RouteID]
GO


